howareyou/urls.py
from django.urls import path
from .views import status_create

app_name = 'howareyou'

urlpatterns = [
    path('', status_create, name='status_create'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('howareyou.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
]

story7/urls.py
from django.urls import path
from .views import myprofile

app_name = 'story7'

urlpatterns = [
    path('', myprofile, name='myprofile'),
]

story8/urls.py
from django.urls import path
from .views import bookSearch

app_name = 'story8'

urlpatterns = [
    path('', bookSearch, name='bookSearch'),
]

howareyou/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Status(models.Model):
    status = models.CharField(null=False, blank=False, max_length = 301)
    date = models.DateTimeField(default = timezone.now)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

howareyou/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = {'status'}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'id': 'status',
            })

howareyou/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm

def status_create(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('howareyou:status_create')
    else:
        form = StatusForm()
    data = Status.objects.all()
    return render(request, 'howareyou.html', {'form': form, 'data': data})

story7/views.py
from django.shortcuts import render

# Create your views here.
def myprofile(request):
    return render(request, 'myprofile.html')

story8/views.py
from django.shortcuts import render

# Create your views here.

def bookSearch(request):
    return render(request, 'bookSearch.html')

howareyou/templates/howareyou.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>How Are You</title>
    <link rel="icon" type="image/png" href="{% static 'question.png' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <div class="header">
        <h1 class="text-center mt-3 my-header">Hello, How Are You ?</h1>
        <form class="text-center" method="POST" action="{% url 'howareyou:status_create' %}">
            {% csrf_token %}
            
              <div id="id_status" class="form-group text-center">
                {{ form.status }}
              </div>
            <button id="submit" type="submit" class="btn btn-primary">
              Send
            </button>
        </form>
    </div>
    <hr/>
    <div class="content">
        <div class="row">
            {% for item in data %}
            <div class="col-lg-4 my-schedule text-center">
                <p class="my-title mb-2">
                  {{ item.status }}
                </p>
                 <p class="my-date">
                    {{ item.date }}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
  </div>
</body>
</html>

story7/templates/myprofile.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My Profile | Portfolio</title>
  <link rel="icon" type="image/png" href="{% static 'img/ali.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="white">
  
    <div class="container text-center">
      
      <div class="row">
          <header class="py-5">
              <h1 class="font-weight-light">My Profile</h1>
          </header>
          
      </div>
      
      <div class="row">
        <div class="col">
            <div class="card p-2 dark-bg">
                <img src="{% static 'img/ali.png' %}" alt="Ali" style="width:100%">
                <h3>Ali Irsyaad Nursyaban</h3>
                <p class="title">Web Developer, Ethical Hacker</p>
                <p>Universitas Indonesia | Computer Science</p>
                <div class="col mb-4">
                  <!-- LinkedIn -->
                  <a class="p-2 fa-lg fb-ic" href="https://id.linkedin.com/in/ali-irsyaad-nursyaban-519ab2125" target="_blank">
                    <i class="fab fa-linkedin text-white-50"> </i>
                  </a>
                  <!-- Twitter -->
                  <a class="p-2 fa-lg tw-ic" href="https://twitter.com/A_Irsyaad_N" target="_blank" >
                    <i class="fab fa-twitter text-white-50"> </i>
                  </a>
                  <!-- Instagram -->
                  <a class="p-2 fa-lg ins-ic" href="https://www.instagram.com/ali_irsyaad/" target="_blank">
                    <i class="fab fa-instagram text-white-50"> </i>
                  </a>
                </div>
            </div>
        </div>
        <div class="col">
            <ul class="child">
                <li class='acc-list'>
                  <a class="panels" href="#">Activities</a>
                  <ul class="inside">
                      <li>Student</li>
                      <li>Sports</li>
                      <li>IT</li>
                  </ul>
                </li>
  
                <li class='acc-list'>
                  <a class="panels" href="#">Experiences</a>
                  <ul class="inside">
                    <li>Chairman of <strong>Gerakan Cinta Lingkungan 34</strong> </li>
                    <li>Leader of Event <strong>INTEGER 2018</strong></li>
                    <li>Staff of Workshop <strong>Educare Fasilkom UI 2018</strong></li>
                    <li>Staff of Decoration and Costume <strong>COMPFEST 11</strong></li>
                  </ul>
                </li>
  
                <li class='acc-list'>
                  <a class="panels test-accordion" href="#">Achievements</a>
                  <ul class="inside">
                    <li>1st Place in JKTC Pencak Silat Class E</li>
                  </ul>
                </li>
  
                <li class='acc-list'>
                  <a class="panels" href="#">Educations</a>
                  <ul class="inside">
                    <li>SDN 01 Lebak Bulus</li>
                    <li>SMPN 85 Jakarta</li>
                    <li>SMAN 34 Jakarta</li>
                    <li>University of Indonesia, Computer Science Undergraduate</li>
                  </ul>
                </li>
            </ul>
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" id="switch">
                  <label class="custom-control-label switch-label" for="switch">White Mode</label>
                </div>
        </div> 
      </div>
    </div>
   
  
  
 
  <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
  <script src = "{% static 'js/accordion.js' %}"></script>
  <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
  <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
  <script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>

</body>
</html>

story8/templates/bookSearch.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Story 8 | BookSearch</title>
  <link rel="icon" type="image/png" href="{% static 'img/book.png' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="text-center">
  
    
  <h1 class="mt-4 title">Book Search</h1>

    <input style="width: 75%;" type="text" id="key">
    <button class="btn-primary"type="button" id="search">Search</button>

  <div id="content" class="row"></div>
  
  <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
  <script src = "{% static 'js/index.js' %}"></script>
  <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
  <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
  <script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>

</body>
</html>